### ISSUE TITLE
Release Model

### ISSUE THREAD

**Issue by huanzhang12** [MadryLab/mnist_challenge#1]
Are you going to release the challenge model very soon? It is Oct 19th now. Thanks!

**Comment by dtsip** [comment]
Yes, we are releasing the model very soon. We want to initialize a leaderboard for white-box attacks together with the model release. We are kind of swamped these days so this is taking longer than expected. Sorry for the delay!

**Comment by huanzhang12** [comment]
Thank you! I will really appreciate it if you can release the model soon because we are working on a ICLR paper and we would like to use the model and cite your work ;)

**Comment by dtsip** [comment]
... and it's released. :)
Running `python fetch_model.py secret` will download it.
