### ISSUE TITLE
Any adversarial attack that sustains after resize attack?

### ISSUE THREAD

**Issue by BalaMallikarjuna-G** [MadryLab/mnist_challenge#11]
Is there any adversarial attack that sustains/consists of added noise, after resize attack ? (adversarial image -> converting into High / low resolution image -> resize to original adverarial image size)

**Comment by dtsip** [comment]
I am not aware of any such attack but it should be possible in principle. Since up/down-scaling images is a differentiable operation, one can incorporate it directly into PGD.

**Comment by BalaMallikarjuna-G** [comment]
Thanks for your reply. I checked with PGD and BIM attacks using foolbox.
But after re-size attack (28x28 -> 65x75 ->28x28) , the added noise is
removed or disturbed.
please let me know your suggestions.

sorry for the late reply. I was out of work for last few days.

**Comment by dtsip** [comment]
So the idea would be add a layer between the input and the first network layer that performs this resize attack (lo -> hi -> lo def). Then attack this augmented network with a standard method (PGD). The adversarial example you find will be adversarial even after resizing.
