### ISSUE TITLE
Adversarial performance for MNIST models vary widely with different random seed initializations

### ISSUE THREAD

**Issue by hangletn** [MadryLab/mnist_challenge#14]
Hello, thank you for the repo. I'm trying to reproduce the results that you reported in the paper. In the process, I used different seeds to initialize the weight matrix (8 different seeds) and I observe that the adversarial performance vary widely for the standard model without adversarial training (for eps = 0.3, the range is 0.02%-2.2%). I wonder whether you have tested the model with different random initialization seeds and whether you also see such high variance in the performance. Thank you very much!

**Comment by dtsip** [comment]
Hi, we did observe some variance when training from a different random initialization. The resulting robust accuracy would often change by 1-2%.
