### ISSUE TITLE
Are there any Pytorch version of this challenge? Cause tensorflow usually has conflict with my Pytorch.

### ISSUE THREAD

**Issue by Asber777** [MadryLab/mnist_challenge#16]
Are there any Pytorch version of this challenge? Cause tensorflow usually has conflict with my Pytorch.As I using Advertorch as attack lib. But I came across the problem that version conflict between torch and tensor flow.

**Comment by dtsip** [comment]
There is no pytorch version per se. But if you are interested in attacking robust, pre-trained models, you might find the [robustness library](https://github.com/MadryLab/robustness) useful.

**Comment by Asber777** [comment]
> There is no pytorch version per se. But if you are interested in attacking robust, pre-trained models, you might find the [robustness library](https://github.com/MadryLab/robustness) useful.

Thanks very much, that's really helpful.
