### ISSUE TITLE
about version

### ISSUE THREAD

**Issue by lsy-sunny** [MadryLab/mnist_challenge#17]
When I want to run this code, there will always be version incompatibility。
Could you tell me about the version of the python and tensorflow?

**Comment by dtsip** [comment]
Unfortunately we are not actively maintaining this project and we have thus not tested it with recent versions of tensorflow. I think your best bet is to use the versions that were standard during the development of the code, that is Summer 2017.

At the same time, you might be interested in the [robustness library](https://github.com/MadryLab/robustness) which is more recent and contains all the relevant code for training and evaluating adversarially robust models.
