### ISSUE TITLE
Question about reproducing your results

### ISSUE THREAD

**Issue by liuchihuang** [MadryLab/mnist_challenge#4]
Hello! I tried to reproduce your result but only got adversarial accuracy of 90.44% which is less than the 93.2% reported in your paper. Did you use different parameters from those in this code?

**Comment by dtsip** [comment]
Hi, there might be minor differences but nothing significant. We used the repository code to train the released pre-trained model (`python fetch_model.py secret`) which gets 92.52% accuracy against single start 100-step PGD. At some point we noticed that sometimes different random seeds lead to different robust accuracies (most seeds get ~93% but some others get ~90%). So you might want to try with a different seed.

**Comment by liuchihuang** [comment]
Thanks for the quick reply and clarification. I'll give it a try.
