### ISSUE TITLE
About random restart

### ISSUE THREAD

**Issue by jinghuichen** [MadryLab/mnist_challenge#6]
Hi, interesting work! I have some questions about random restart and hope you could answer it for me.
I saw from the code it basically add random perturbation before PGD step. but i don't understand what is the meaning for restarts 20 in your Table 1 in the paper? Does it mean attack for 20 times and take average? BTW, is this restart very important for the final performance. Do you test it with no random restart, can it retain the accuracy or it will be worse? Thanks

**Comment by dtsip** [comment]
During training we perform random _start_, i.e. we add a random perturbation before the first PGD step. During eval, we test PGD from multiple random starts and keep the worst. That is we run a full PGD attack from (say) 20 different random starts and consider an classifier successful only if it was not fooled by _any_ of these 20 attacks. As you can see, an attack that uses a bunch of restarts reduces the robust accuracy by a few percent compared to a single start attack. Using a random start during training is not essential, you can set `random_start` to `false` and you will get comparable results.

**Comment by jinghuichen** [comment]
Thanks!
