### ISSUE TITLE
parameters for train robust adv_trained/secret networks?

### ISSUE THREAD

**Issue by nooooonee** [MadryLab/mnist_challenge#8]
Could I know how many iterations you used to train adv_trained/secret network (those have published)?   Indeed, they are very robust to resist CW attacks after I tested on mnist. And I try to train a robust network from scratch. I run your source code with the untouched setting( iterations= 100,000 and batch size =50) in config.json, however, I cannot get a very robust network against CW attack. I wonder if I don't train with enough iterations. Any help will be appreciated!

**Comment by dtsip** [comment]
Both the adv_trained and secret networks were trained for 100k iterations. You can find the exact `config.json` used inside the model directory.
